@startuml
'https://plantuml.com/class-diagram

!include Incidente.puml
!include IncidentePorComunidad.puml
!include RevisionIncidente.puml

IncidentePorComunidad --> Incidente

RevisionIncidente --> Incidente


@enduml