@startuml
'https://plantuml.com/class-diagram

class Incidente{
    - serviciosAfectados: List<ServicioPrestado>
    - observaciones: String
    - fechaApertura: DateTime
    - autorApertura: Persona
    +getInfo(): String
}
@enduml