@startuml
'https://plantuml.com/class-diagram

class IncidentePorComunidad {
    - incidente: Incidente
    - estaCerrado: boolean
    - fechaHoraCierre: LocalDateTime
    - autorCierre: Persona

}

@enduml