@startuml
'https://plantuml.com/class-diagram


skinparam linetype ortho

class Incidente {
  - id: int
  - autorApertura: Persona
  - fechaHoraApertura: LocalDateTime
  - observaciones: String
  - servicioPrestados: List<ServicioPrestado>

  + agregarIncidenteComunidad(): void
  + getInfo(): String
  + obtenerEntidad(): Entidad
  + agregarServiciosPrestados(List<ServicioPrestado>): void
}

@enduml