@startuml

skinparam linetype ortho
skinparam ranksep 50

'https://plantuml.com/class-diagram
'Para que las flechas hagan caso a veces hay que repetir
!include E3/notificaciones.puml
!include E3/domain.puml
'!include E3/hasheo.puml
'!include E3/importadorEntidades.puml
!include E3/meta_datos_geo.puml
!include E3/notificaciones.puml
!include E3/rankings.puml
!include E3/validacion.puml

Persona ..> Notificable
ListadoNotificables -->"*" Notificable
ListadoNotificables ..|> Notificable


StrategyNotificacion ..> Persona

IncidentePorComunidad <.. EstrategiaCalculoPuntos
Entidad <.. EstrategiaCalculoPuntos

Entidad <-- PuntosPorEntidad

Entidad "*"<-- Ranking

IncidentePorComunidad <.. MedidorImpacto
Entidad <.. MedidorImpacto

ValidadorUsuario ..> Usuario
Ubicacion --> Provincia
Ubicacion --> Localidad
Ubicacion --> AdapterProveedorMetadatosGeograficos

Informe --> Informable
Informe ..|> Notificable
@enduml