@startuml
'https://plantuml.com/class-diagram

class GeneradorRanking{
 - generadorPuntos: EstrategiaCalculoPuntos
 + generarRanking(incidentes: List<IncidentePorComunidad>,descripcion: String): Ranking
}

@enduml