# Use postgres/example user/password credentials
version: '3.1'

services:

  dbservice:
    image: postgres
    restart: always
    ports:
      - 8090:5432
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: pruebas
    volumes:
      - ./posgresdb:/var/lib/postgresql/data

  app:
    image: main-project
    restart: always
    ports:
      - 8080:8080
    environment:
      APP_MAIN_PORT: 8080
      DB_CONNECTION_HIBERNATE_HBM2DDL_AUTO: update
      DB_CONNECTION_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      DB_CONNECTION_DRIVER_CLASS: org.postgresql.Driver
      DB_CONNECTION_PASSWORD: 123
      DB_CONNECTION_HOST: jdbc:postgresql://dbservice/pruebas
      DB_CONNECTION_USERNAME: postgres
      DB_CONNECTION_HIBERNATE_SHOW_SQL: TRUE
      SERVICIO_CALCULO_GRADO_CONFIANZA_URL: http://localhost:9999
      SERVICIO_FUSION_URL: http://localhost:9998
      LISTADO_INCIDENTES_URL: http://localhost:9997/incidentes
      NOTIFICACION_PENDIENTES_MINUTOS: 30
      NOTIFICACION_AL_MOMENTO_MINUTOS: 5
      GENERAR_RANKING_DIA: MONDAY
      GENERAR_RANKING_HORA: 00:00
      CALCULAR_CONFIANZA_DIA: SUNDAY
      CALCULAR_CONFIANZA_HORA: 13:00
      WORST_PASSWORDS_FILE: public/validacion/10000WorstPasswords.txt
      CRON_TASK_PERIODO_REFRESCO_MIN: 1
    depends_on:
      - dbservice
