@startuml
'https://plantuml.com/class-diagram

class Ubicacion{
    - coordenada: Coordenada
    - metadato: MetadatoGeografico
    -adapterMetadatosGeograficos: AdapterMetadatosGeograficos

    + cargarMetadatosGeograficos(): void
    + estaCercaDe(ubicacion: Ubicacion): boolean
}
@enduml