@startuml
'https://plantuml.com/class-diagram

skinparam linetype ortho

!include comunidades/Comunidad.puml
!include comunidades/Interes.puml
!include comunidades/Membresia.puml
!include comunidades/Persona.puml
!include comunidades/Usuario.puml
!include comunidades/Rol.puml
!include comunidades/Permiso.puml

!include comunidades/notificacionesPersona/ListadoNotificables.puml
!include comunidades/notificacionesPersona/NotificacionAlMomento.puml
!include comunidades/notificacionesPersona/NotificacionSinApuro.puml
!include comunidades/notificacionesPersona/EstrategiaMomentoNotificacion.puml
!include comunidades/notificacionesPersona/Horario.puml

Persona --> EstrategiaMomentoNotificacion
Persona --> Interes
Persona --> "1..*" Membresia
Persona --> Usuario

Membresia --> Persona
Membresia --> Comunidad
Membresia --> Rol

Rol -->"*" Permiso

Comunidad --> "1..*" Membresia



NotificacionSinApuro ..|> EstrategiaMomentoNotificacion
NotificacionSinApuro --> ListadoNotificables
NotificacionSinApuro -->"*" Horario
NotificacionAlMomento ..|> EstrategiaMomentoNotificacion



@enduml