@startuml
'https://plantuml.com/class-diagram

skinparam PackageBorderThickness 4
skinparam PackageBorderColor DarkSlateGray

package Entidades{
!include entidades/entidades.puml
}

package Servicios{
!include servicios/servicios.puml
}

package Incidentes{
!include incidentes/incidentes.puml
IncidentePorComunidad --> ServicioPrestado
}

package Utilidades{
!include utilidades/utilidades.puml
}

package Comunidades{
!include comunidades/comunidades.puml
Comunidad -->"*" Servicio
Comunidad --> "1..*" IncidentePorComunidad
Comunidad ..> Incidente

Persona --> Ubicacion

}

package Entidades{
OrganismoControl --> Persona
EntidadPrestadora -> Persona
EntidadPrestadora --> InformacionAdpater

Entidad --> Ubicacion

Establecimiento -->"*" Ubicacion
Establecimiento <-- ServicioPrestado

interface InformacionAdpater
}
package Rankings{
!include rankings/rankings.puml
IncidentePorComunidad <.. GeneradorRanking
Entidad <-- Ranking


IncidentePorComunidad <.. MedidorImpacto
Entidad <.. MedidorImpacto

}



@enduml