@startuml
'https://plantuml.com/class-diagram


!include entidades/Denominacion.puml
!include entidades/Entidad.puml
!include entidades/EntidadPrestadora.puml
!include entidades/Establecimiento.puml
!include entidades/OrganismoControl.puml

OrganismoControl -->"*" EntidadPrestadora
EntidadPrestadora -->"*" Entidad
Entidad <-- Establecimiento
Entidad -->"*" Establecimiento

Entidad --> Denominacion
Establecimiento --> Denominacion



@enduml