@startuml
'https://plantuml.com/class-diagram

!include incidentes/Incidente.puml
!include incidentes/IncidentePorComunidad.puml
!include incidentes/RevisionIncidente.puml

IncidentePorComunidad --> Incidente

RevisionIncidente --> Incidente


@enduml