@startuml
'https://plantuml.com/class-diagram

!include servicios/Servicio.puml
!include servicios/ServicioPrestado.puml
!include servicios/Etiqueta.puml

ServicioPrestado --> Servicio
Servicio -->"*" Etiqueta

@enduml