@startuml
'https://plantuml.com/class-diagram

!include utilidades/Ubicacion.puml
!include utilidades/InformacionAdapter.puml
!include utilidades/DistanciaEnMetros.puml
!include utilidades/DistanciaEntrePuntos.puml

DistanciaEntrePuntos ..> Ubicacion
DistanciaEnMetros ..|> DistanciaEntrePuntos
@enduml