@startuml
'https://plantuml.com/class-diagram
package "Metadatos Geograficos"{
    !include meta_datos_geo/AdapterMetadatosGeograficos.puml
    !include meta_datos_geo/Provincia.puml
    !include meta_datos_geo/Municipio.puml
    !include meta_datos_geo/Localidad.puml

    AdapterMetadatosGeograficos ..> Provincia
    AdapterMetadatosGeograficos ..> Municipio
    AdapterMetadatosGeograficos ..> Localidad

    Provincia -->"*" Municipio
    Municipio -->"*" Localidad

}

@enduml