@startuml
'https://plantuml.com/class-diagram
skinparam linetype ortho
package Rankings{
    !include rankings/GeneradorRanking.puml
    !include rankings/EstrategiaCalculoPuntos.puml
    !include rankings/MedidorImpacto.puml
    !include rankings/GradoDeImpacto.puml
    !include rankings/PromedioEntreAperturaYCierre.puml
    !include rankings/MasIncidentesEnSemana.puml
    !include rankings/Ranking.puml


    GeneradorRanking ..> Ranking
    GeneradorRanking --> EstrategiaCalculoPuntos
    MasIncidentesEnSemana ..|> EstrategiaCalculoPuntos
    PromedioEntreAperturaYCierre ..|> EstrategiaCalculoPuntos
    GradoDeImpacto ..|> EstrategiaCalculoPuntos
    GradoDeImpacto --> MedidorImpacto
}
@enduml