@startuml
'https://plantuml.com/class-diagram

skinparam linetype ortho

!include Comunidad.puml
!include Interes.puml
!include Membresia.puml
!include Persona.puml
!include Usuario.puml
!include Rol.puml
!include Permiso.puml

!include notificacionesPersona/ListadoNotificables.puml
!include notificacionesPersona/NotificacionAlMomento.puml
!include notificacionesPersona/NotificacionSinApuro.puml
!include notificacionesPersona/TiempoNotificacion.puml

Persona-->"1..*" Notificable
Persona --> TiempoNotificacion
Persona ..> DistanciaEntrePuntos
Persona --> Interes
Persona ..> Notificable
Persona --> "1..*" Membresia
Persona --> Usuario

Membresia --> Persona
Membresia --> Comunidad
Membresia --> Rol

Rol -->"*" Permiso

Comunidad --> "1..*" Membresia



NotificacionSinApuro ..|> TiempoNotificacion
NotificacionSinApuro --> ListadoNotificables
NotificacionAlMomento ..|> TiempoNotificacion



@enduml