@startuml
'https://plantuml.com/class-diagram

skinparam linetype ortho

class Interes{
    -entidades: List<Entidad>
    -servicios: List<Servicio>

    +agregarEntidad(entidad: Entidad)
    +agregarServicio(servicio: Servicio)
    +eliminarEntidad(entidad: Entidad)
    +eliminarServicio(servicio: Servicio)
    +servicioPrestadoEsDeInteres(servicioPrestado: ServicioPrestado): Boolean
}

@enduml