@startuml
'https://plantuml.com/class-diagram

skinparam linetype ortho

class Membresia{
    -usuario: Persona
    -comunidad: Comunidad
    -rolComunidad: Rol
    -serviciosObservados: List<Servicio>

    +estaAfectado(servicio: Servicio): boolean
}

@enduml