@startuml
'https://plantuml.com/class-diagram

skinparam linetype ortho


class Persona {
  - apellido: String
  - email: String
  - interes: Interes
  - membresias: List<Membresia>
  - metodoNotificacion: String
  - nombre: String
  - tiempoNotificacion: TiempoNotificacion
  - ubicacionActual: Ubicacion
  - usuario: Usuario
  - whatsapp: int

  + agregarEntidadDeInteres(Entidad): void
  + agregarEntidadInteres(Entidad): void
  + agregarMembresia(Membresia): void
  + agregarMembresiaDirecto(Membresia): void
  + agregarServicioDeInteres(Servicio): void
  + agregarServicioInteres(Servicio): void
  + cerrarIncidente(Incidente): void
  + eliminarEntidadDeInteres(Entidad): void
  + eliminarEntidadInteres(Entidad): void
  + eliminarMembresia(Membresia): void
  + eliminarMembresiaDirecto(Membresia): void
  + eliminarMembresiaPorComunidad(Comunidad): void
  + eliminarServicioDeInteres(Servicio): void
  + eliminarServicioInteres(Servicio): void
  + enviarNotificacion(Notificable): void
  + servicioPrestadoEsDeInteres(ServicioPrestado): boolean
  }
@enduml