package ar.edu.utn.frba.dds.controllers.utils;

import java.util.Arrays;
import java.util.List;

public enum TipoPermiso{
    USER_BASE,
    ADMINISTRAR_USUARIOS,
    ADMINISTRAR_COMUNIDAD,
    ADMINISTRAR_ENTIDADES,
    ADMINISTRAR_ENTIDADES_PRESTADORAS,
    ADMINISTRAR_ORGANISMOS_DE_CONTROL,
    ADMINISTRAR_SERVICIOS,
    ADMINISTRAR_ESTABLECIMIENTOS,
    ADMINISTRAR_SERVICIOS_PRESTADOS,
    ADMINISTRAR_ETIQUETAS,
    ADMINISTRAR_ROLES
}