@startuml
'https://plantuml.com/class-diagram


!include Denominacion.puml
!include Entidad.puml
!include EntidadPrestadora.puml
!include Establecimiento.puml
!include OrganismoControl.puml

OrganismoControl -->"*" EntidadPrestadora
EntidadPrestadora -->"*" Entidad
Entidad <-- Establecimiento
Entidad -->"*" Establecimiento

Entidad --> Denominacion
Establecimiento --> Denominacion



@enduml