@startuml
'https://plantuml.com/class-diagram

class Establecimiento{
    - entidad: Entidad
    - nombre: String
    - id: int
    - denominacion : Denominacion
    - serviciosPrestados : List<ServicioPrestado>
    - ubicacion : Ubicacion

    + agregarServicio(nuevo: Servicio)
    + eliminarServicio(servicio: Servicio)
    + eliminarServicioPrestado(servicio: ServicioPrestado)
}

@enduml