@startuml
'https://plantuml.com/class-diagram

class OrganismoControl{
    - entidades: List<EntidadPrestadora>
    - nombre : String
    - informado: Persona
    - generadorInformacion: InformacionAdapter

    +enviarInformacion()
}

@enduml