@startuml
'https://plantuml.com/class-diagram

class MasIncidentesEnSemana{
+ calcularPuntos(incidentes: List<IncidentePorComunidad>): Map<Entidad,Double>
- ordenarIncidentes(incidentes: List<IncidentePorComunidad>): List<Incidente>
- incidentes24HorasPorEntidad(incidentes: List<IncidentePorComunidad>): Map<Entidad,List<Incidente>>
}

@enduml