@startuml
'https://plantuml.com/class-diagram
skinparam linetype ortho
package Rankings{
    !include GeneradorRanking.puml
    !include EstrategiaCalculoPuntos.puml
    !include MedidorImpacto.puml
    !include GradoDeImpacto.puml
    !include PromedioEntreAperturaYCierre.puml
    !include MasIncidentesEnSemana.puml
    !include Ranking.puml


    GeneradorRanking ..> Ranking
    GeneradorRanking --> EstrategiaCalculoPuntos
    MasIncidentesEnSemana ..|> EstrategiaCalculoPuntos
    PromedioEntreAperturaYCierre ..|> EstrategiaCalculoPuntos
    GradoDeImpacto ..|> EstrategiaCalculoPuntos
    GradoDeImpacto --> MedidorImpacto
}
@enduml