@startuml
'https://plantuml.com/class-diagram
skinparam linetype ortho

!include GeneradorRanking.puml
!include MedidorImpacto.puml
!include GradoDeImpacto.puml
!include PromedioEntreCierre.puml
!include MasIncidentesEnSemana.puml
!include Ranking.puml


GeneradorRanking ..> Ranking
MasIncidentesEnSemana ..|> GeneradorRanking
PromedioEntreCierre ..|> GeneradorRanking
GradoDeImpacto ..|> GeneradorRanking
GradoDeImpacto --> MedidorImpacto

@enduml