@startuml
'https://plantuml.com/class-diagram

interface AdapterProveedorMetadatosGeograficos << interface >> {
  + obtenerMetadatoGeografico(coordenada: Coordenada): MetadatoGeografico
  + obtenerProvincia(coordenada: Coordenada): Provincia
  + obtenerDepartamento(coordenada: Coordenada): Departamento
  + obtenerLocalidad(coordenada: Coordenada): Localidad
  + obtenerMunicipio(coordenada: Coordenada): Municipio
  + provincias() : List<Provincia>
  + departamentosDeProvincia(unaProvincia: Provincia): List<Departamento>
  + localidadesDeProvincia(unaProvincia: Provincia): List<Localidad>
  + municipiosDeProvincia(unaProvincia: Provincia): List<Municipio>
}

@enduml