@startuml Usuario y Validacion
skinparam linetype ortho

!startsub ValidadorUsuario

class AdministradorUsuario {
    - validadorUsuario: ValidadorUsuario

    + registrarUsuario(nuevoUsuario: Usuario)
}
AdministradorUsuario --> ValidadorUsuario
AdministradorUsuario ..> Usuario
AdministradorUsuario .right.> EstrategiaHash

class ValidadorUsuario{
    - {static} estrategias: List<EstrategiaValidacion>
    
    + inicializar()
    + esValido(usuario: Usuario) : boolean
}
ValidadorUsuario ..> Usuario
ValidadorUsuario -r-> "1..*" EstrategiaValidacion
!endsub

!startsub Usuario


Usuario --> Password

class Usuario{
    -id: int
    -username: String
    -nombre: String
    -apellido: String
    -email: String
    -password: Password
    -sesion: Sesion
    -rolPlataforma: RolPlataforma
    -membresias: List<Miembro>

    + esMiembroDe(comunidad: Comunidad)
    + suscribirAComunidad(comunidad: Comunidad)
    + desuscribirAComunidad(comunidad: Comunidad)
    + cerrarSesion()
    + iniciarSesion(password: String)
    + sesionIniciada()
    + cambiarPassword(viejaPassword: String, nuevaPassword: String)
}
!endsub
Usuario --> RolPlataforma

interface EstrategiaValidacion {
    + validar(cadena: String) : boolean
}

class EstrategiaValidacionRegExp {
    
    - patron: RegExp
    + validar(cadena: String) : boolean
}
EstrategiaValidacionRegExp ..|> EstrategiaValidacion

class EstrategiaValidacionNoEstaEnLista{
    - obtenerListaString: ObtenerListaString
    + validar(cadena: String) : boolean
}
EstrategiaValidacionNoEstaEnLista --> ObtenerListaString
EstrategiaValidacionNoEstaEnLista ..|> EstrategiaValidacion

interface ObtenerListaString {
    + obtenerLista() : List<String>
}

class ObtenerTopPeoresPasswordsURL {
    - url: String
    - lista: List<String>
    + obtenerLista() : List<String>
}
ObtenerTopPeoresPasswordsURL ..|> ObtenerListaString

class Password{
    -hasheado: String
    -estrategiaHash: EstrategiaHash

    + hashear(password: String)
    + esCorrecta(password: String) : boolean
    + cambiarPassword(viejaPassword: String, nuevaPassword: String)
}
Password --> EstrategiaHash

interface EstrategiaHash {
    + hashear(password: String) : String
}

class HashPBKDF2{
    - salt: byte[]
    - costo: int
    + hashear(password: String) : String
}
HashPBKDF2 ..|> EstrategiaHash


class HashMD5 <<ejemplo>>{
    + hashear(password: String) : String
}
HashMD5 ..|> EstrategiaHash

interface RolPlataforma {}

AdministradorPlataforma ..|> RolPlataforma
UsuarioPlataforma ..|> RolPlataforma



@enduml