@startuml

skinparam linetype ortho

class Entidad {
  - id: int
  - denominacion: Denominacion
  - establecimientos: List<Establecimiento>
  - nombre: String
  - ubicacion: Ubicacion

  + agregarEstablecimiento(Establecimiento): void
  + agregarEstablecimiento(Establecimiento, int): void
  + eliminarEstablecimiento(Establecimiento): void
  - eliminarEstablecimientoPorID(int): void
}

@enduml
