@startuml
'https://plantuml.com/class-diagram

skinparam linetype ortho

interface AdapterMetadatosGeograficos << interface >> {
  + obtenerLocalidad(float, float): Localidad
  + obtenerMetadatoGeografico(float, float): MetadatoGeografico
  + obtenerMunicipio(float, float): Municipio
  + obtenerProvincia(float, float): Provincia
}

@enduml